version: "3.8"
services:
  db:
    container_name: unolingua_database
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - default
    environment:
      POSTGRES_DB: unolingua
      POSTGRES_USER: uno
      POSTGRES_PASSWORD: uno13578
    ports:
      - "5888:5432"
  backend:
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - default
    container_name: unolingua_backend
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - db
    ports:
      - "8000:8000"
  