version: "3.8"
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  10.10.0.1/16

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - default
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  backend:
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - default
    container_name: mobile-app-back
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - db
    ports:
      - "8000:8000"
  
