# Generated by Django 3.2.9 on 2021-11-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id_country', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=40, unique=True)),
                ('flag_link', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id_ex', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('num_ex', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
            options={
                'db_table': 'exercises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'favorites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ik',
            fields=[
                ('id_ik', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LecFilling',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lec_filling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LessonBlocks',
            fields=[
                ('id_lb', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lesson_blocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id_les', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('name_les', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'lessons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lexemes',
            fields=[
                ('id_lex', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('mean_lex', models.CharField(max_length=100)),
                ('transcr', models.CharField(blank=True, max_length=100, null=True)),
                ('stress', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'lexemes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id_med', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('link_med', models.TextField()),
            ],
            options={
                'db_table': 'media',
                'managed': False,
            },
        ),
        # migrations.CreateModel(
        #     name='Newletters',
        #     fields=[
        #         ('id_key', models.IntegerField(primary_key=True, serialize=False)),
        #         ('id_task', models.DecimalField(decimal_places=0, max_digits=5)),
        #         ('id_ex', models.DecimalField(decimal_places=0, max_digits=5)),
        #         ('num_task', models.DecimalField(decimal_places=0, max_digits=2)),
        #         ('mean_lex', models.CharField(max_length=100)),
        #         ('med_type', models.CharField(max_length=11)),
        #         ('link_med', models.TextField()),
        #     ],
        #     options={
        #         'db_table': 'New_letters',
        #         'managed': False,
        #     },
        # ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('login', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeopleGroups',
            fields=[
                ('group_user', models.CharField(max_length=13, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'people_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('mean_pr', models.BooleanField()),
            ],
            options={
                'db_table': 'progress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('id_red', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('mean_red', models.TextField()),
            ],
            options={
                'db_table': 'reduction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReductionLexemes',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'reduction_lexemes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Replicas',
            fields=[
                ('id_rep', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('time_start', models.TimeField()),
                ('time_finish', models.TimeField()),
                ('med_ik', models.TextField()),
            ],
            options={
                'db_table': 'replicas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id_task', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('num_task', models.DecimalField(decimal_places=0, max_digits=2)),
                ('num_lex', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('count_miss', models.DecimalField(blank=True, decimal_places=0, max_digits=50, null=True)),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypesEx',
            fields=[
                ('type_ex', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('mean_type_ex', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'types_ex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypesLex',
            fields=[
                ('type_lex', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'types_lex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypesMed',
            fields=[
                ('type_med', models.CharField(max_length=11, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'types_med',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('num_miss', models.DecimalField(blank=True, decimal_places=0, max_digits=101, null=True)),
            ],
            options={
                'db_table': 'variants',
                'managed': False,
            },
        ),
    ]
