# Generated by Django 3.2.9 on 2021-12-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rules',
            table='rules',
        ),
        migrations.AlterModelTable(
            name='ruleslexemes',
            table='rules_lexemes',
        ),
    ]
