# Generated by Django 3.2.9 on 2022-01-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211206_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Status',
                'managed': False,
            },
        ),
    ]
