# Generated by Django 3.2.9 on 2021-11-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newletters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newwords',
            fields=[
                #('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.DecimalField(primary_key=True,decimal_places=0, max_digits=5, serialize=False)),
                ('id_ex', models.DecimalField(decimal_places=0, max_digits=5)),
                ('num_task', models.DecimalField(decimal_places=0, max_digits=2)),
                ('mean_lex', models.CharField(max_length=100)),
                ('med_type', models.CharField(max_length=11)),
                ('link_med', models.TextField()),
            ],
            options={
                'db_table': 'new_words',
                'managed': False,
            },
        ),
    ]
