# Generated by Django 3.2.9 on 2022-01-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
    ]
