# Generated by Django 3.2.9 on 2021-11-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_newwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newphrases',
            fields=[
                ('id_task', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('id_ex', models.DecimalField(decimal_places=0, max_digits=5)),
                ('num_task', models.DecimalField(decimal_places=0, max_digits=2)),
                ('mean_lex', models.CharField(max_length=100)),
                ('med_type', models.CharField(max_length=11)),
                ('link_med', models.TextField()),
            ],
            options={
                'db_table': 'new_phrases',
                'managed': False,
            },
        ),
    ]
