# Generated by Django 3.2.9 on 2021-11-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_newphrases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchsyllablessound',
            fields=[
                ('id_task', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('id_ex', models.DecimalField(decimal_places=0, max_digits=5)),
                ('num_task', models.DecimalField(decimal_places=0, max_digits=2)),
                ('mean_lex', models.CharField(max_length=100)),
                ('right_sound', models.TextField()),
                ('wrong_sound', models.TextField()),
            ],
            options={
                'db_table': 'match_syllables_sound',
                'managed': False,
            },
        ),
    ]
