# Generated by Django 3.2.9 on 2022-02-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vowelsound'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowInfoAboutRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_les', models.IntegerField()),
                ('name_les', models.CharField(max_length=100)),
                ('id_ex', models.DecimalField(decimal_places=0, max_digits=5)),
                ('num_ex', models.IntegerField()),
                ('id_r', models.DecimalField(decimal_places=0, max_digits=5)),
                ('id_task', models.TextField()),
                ('picture', models.TextField()),
                ('sound_rule', models.FileField(upload_to="images/sound/")),
                ('side', models.CharField(max_length=5)),
                ('mean_lex', models.TextField()),
                ('var_lex', models.TextField()),
                ('var_transcr', models.TextField()),
                ('var_sound', models.FileField(upload_to="images/sound/")),
                ('var_pic', models.TextField()),
                ('mean_type_ex', models.TextField()),
            ],
            options={
                'db_table': 'show_info_about_rules',
                'managed': False,
            },
        ),
    ]
