# Generated by Django 3.2.9 on 2021-11-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_collectwordsletters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missingletter',
            fields=[
                ('id_task', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('id_ex', models.DecimalField(decimal_places=0, max_digits=5)),
                ('num_task', models.DecimalField(decimal_places=0, max_digits=2)),
                ('word', models.CharField(max_length=100)),
                ('num_lex', models.DecimalField(decimal_places=0, max_digits=1)),
                ('count_miss', models.DecimalField(decimal_places=0, max_digits=50)),
                ('num_miss', models.DecimalField(decimal_places=0, max_digits=101)),
                ('letter', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'missing_letter',
                'managed': False,
            },
        ),
    ]
