# Generated by Django 3.2.9 on 2022-02-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_showinfoaboutwordsletters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowInfoAboutPhrase',
            fields=[
                ('id_les', models.IntegerField()),
                ('name_les', models.CharField(max_length=100)),
                ('id_ex', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('num_ex', models.IntegerField()),
                ('id_task', models.TextField()),
                ('num_task', models.TextField()),
                ('replica', models.TextField()),
                ('ik', models.TextField()),
                ('pic_video', models.FileField(upload_to="images/", db_column='pic/video', null=True, blank=True)),
                ('sound2', models.FileField(upload_to="images/", null=True, blank=True)),
                ('var', models.TextField()),
                ('miss', models.TextField()),
                ('mean_type_ex', models.TextField()),
            ],
            options={
                'db_table': 'show_info_about_phrase',
                'managed': False,
            },
        ),
    ]
