# Generated by Django 3.2.9 on 2022-04-26 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makevideo', '0002_delete_videocommands'),
        ('api', '0008_showinfoaboutphrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('num_ex', models.DecimalField(decimal_places=0, max_digits=2)),
                ('picture', models.TextField()),
                ('type', models.ForeignKey(db_column='type_ex', on_delete=django.db.models.deletion.DO_NOTHING, to='api.typesex')),
            ],
        ),
        migrations.CreateModel(
            name='ForLessonsDTO',
            fields=[
                ('id_les', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name_les', models.CharField(max_length=100)),
                ('lessonblock', models.ForeignKey(db_column='id_lb', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ForLessonsDTO_lesson_info', to='api.lessonblocks')),
                ('video', models.ForeignKey(blank=True, db_column='id_v', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ForLessonsDTO_video', to='makevideo.video')),
            ],
        ),
        migrations.CreateModel(
            name='LessonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog_st', models.ForeignKey(db_column='dialog_st', default='Пусто', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ForLessonsDTO_status_dialog_st', to='api.status')),
                ('lex_st', models.ForeignKey(db_column='lex_st', default='Пусто', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ForLessonsDTO_status_lex_st', to='api.status')),
                ('phr_st', models.ForeignKey(db_column='phr_st', default='Пусто', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ForLessonsDTO_status_phr_st', to='api.status')),
                ('rules_st', models.ForeignKey(db_column='rules_st', default='Пусто', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ForLessonsDTO_status_rules_st', to='api.status')),
                ('video_st', models.ForeignKey(db_column='video_st', default='Пусто', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ForLessonsDTO_status_video_st', to='api.status')),
            ],
        ),
        migrations.CreateModel(
            name='Lex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('num_ex', models.DecimalField(decimal_places=0, max_digits=2)),
                ('id_lex', models.ManyToManyField(blank=True, null=True, related_name='ForLessonsDTO_lex_id_lex', to='api.Lexemes')),
                ('id_miss', models.ManyToManyField(blank=True, null=True, related_name='ForLessonsDTO_lex_id_miss', to='api.Lexemes')),
                ('id_variant', models.ManyToManyField(blank=True, null=True, related_name='ForLessonsDTO_lex_id_variant', to='api.Lexemes')),
                ('type', models.ForeignKey(db_column='type_ex', on_delete=django.db.models.deletion.DO_NOTHING, to='api.typesex')),
            ],
        ),
        migrations.CreateModel(
            name='Phrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('num_ex', models.DecimalField(decimal_places=0, max_digits=2)),
                ('id_miss', models.ManyToManyField(blank=True, null=True, related_name='ForLessonsDTO_phrases_id_miss', to='api.Lexemes')),
                ('id_variant', models.ManyToManyField(blank=True, null=True, related_name='ForLessonsDTO_phrases_id_variant', to='api.Lexemes')),
                ('lexeme', models.ForeignKey(db_column='id_lex', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.lexemes')),
                ('type', models.ForeignKey(db_column='type_ex', on_delete=django.db.models.deletion.DO_NOTHING, to='api.typesex')),
            ],
        ),
        migrations.DeleteModel(
            name='Collectwordsletters',
        ),
        migrations.DeleteModel(
            name='Matchsyllablessound',
        ),
        migrations.DeleteModel(
            name='Missingletter',
        ),
        migrations.DeleteModel(
            name='Newletters',
        ),
        migrations.DeleteModel(
            name='Newphrases',
        ),
        migrations.DeleteModel(
            name='Newwords',
        ),
        migrations.DeleteModel(
            name='Pronunciationwords',
        ),
        migrations.DeleteModel(
            name='Recoverphrases',
        ),
        migrations.DeleteModel(
            name='Selectwords',
        ),
        migrations.DeleteModel(
            name='Wordpicturematch',
        ),
        migrations.DeleteModel(
            name='Wordpictureselect',
        ),
        migrations.DeleteModel(
            name='Writewords',
        ),
    ]
