# Generated by Django 3.2.9 on 2021-11-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pronunciationwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recoverphrases',
            fields=[
                ('id_task', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('id_ex', models.DecimalField(decimal_places=0, max_digits=5)),
                ('num_task', models.DecimalField(decimal_places=0, max_digits=2)),
                ('word', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'recover_phrases',
                'managed': False,
            },
        ),
    ]
