# Generated by Django 3.2.9 on 2022-04-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220426_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forlessonsdto',
            name='video',
            field=models.ForeignKey(blank=True, db_column='id_v', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ForLessonsDTO_lessoninfo', to='api.lessoninfo'),
        ),
    ]
