# Generated by Django 3.2.9 on 2021-11-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_selectwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordpicturematch',
            fields=[
                ('id_task', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('id_ex', models.DecimalField(decimal_places=0, max_digits=5)),
                ('num_task', models.DecimalField(decimal_places=0, max_digits=2)),
                ('var1_lex', models.CharField(max_length=100)),
                ('var1_pic', models.TextField()),
                ('var_lex', models.CharField(max_length=100)),
                ('var_pic', models.TextField()),
            ],
            options={
                'db_table': 'word_picture_match',
                'managed': False,
            },
        ),
    ]
