# Generated by Django 3.2.9 on 2022-04-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220426_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forlessonsdto',
            old_name='id_les',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='forlessonsdto',
            name='lessonblock',
        ),
        migrations.RemoveField(
            model_name='forlessonsdto',
            name='name_les',
        ),
        migrations.RemoveField(
            model_name='forlessonsdto',
            name='video',
        ),
        migrations.DeleteModel(
            name='PhrasesDTO',
        ),
    ]
