# Generated by Django 3.2.9 on 2021-11-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_wordpicturematch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordpictureselect',
            fields=[
                ('id_task', models.DecimalField(decimal_places=0, max_digits=5, primary_key=True, serialize=False)),
                ('id_ex', models.DecimalField(decimal_places=0, max_digits=5)),
                ('num_task', models.DecimalField(decimal_places=0, max_digits=2)),
                ('right_lex', models.CharField(max_length=100)),
                ('right_pic', models.TextField()),
                ('wrong_lex', models.CharField(max_length=100)),
                ('wrong_pic', models.TextField()),
            ],
            options={
                'db_table': 'word_picture_select',
                'managed': False,
            },
        ),
    ]
