# Generated by Django 3.2.9 on 2022-04-26 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makevideo', '0002_delete_videocommands'),
        ('api', '0012_auto_20220426_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='forlessonsdto',
            name='lessonblock',
            field=models.ForeignKey(db_column='id_lb', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ForLessonsDTO_lesson_info', to='api.lessonblocks'),
        ),
        migrations.AddField(
            model_name='forlessonsdto',
            name='name_les',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forlessonsdto',
            name='video',
            field=models.ForeignKey(blank=True, db_column='id_v', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ForLessonsDTO_video', to='makevideo.video'),
        ),
        migrations.CreateModel(
            name='PhrasesDTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('num_ex', models.DecimalField(decimal_places=0, max_digits=2)),
                ('id_miss', models.ManyToManyField(blank=True, null=True, related_name='ForLessonsDTO_phrases_id_miss', to='api.Lexemes')),
                ('id_variant', models.ManyToManyField(blank=True, null=True, related_name='ForLessonsDTO_phrases_id_variant', to='api.Lexemes')),
                ('lexeme', models.ForeignKey(db_column='id_lex', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.lexemes')),
                ('type', models.ForeignKey(db_column='type_ex', on_delete=django.db.models.deletion.DO_NOTHING, to='api.typesex')),
            ],
        ),
    ]
