# Generated by Django 3.2.9 on 2022-04-26 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220426_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoninfodto',
            name='forlesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='foressondto', to='api.forlessonsdto'),
        ),
    ]
