# Generated by Django 3.2.9 on 2022-04-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_lessoninfodto_forlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='rulesdto',
            name='vl_var',
            field=models.ManyToManyField(to='api.Vl'),
        ),
    ]
