# Generated by Django 3.2.9 on 2022-04-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220426_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesdto',
            name='forlesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rules_dto', to='api.forlessonsdto'),
        ),
    ]
