# Generated by Django 3.2.9 on 2022-04-26 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rulesdto_forlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesdto',
            name='id_lex',
            field=models.ForeignKey(blank=True, db_column='id_lex', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ForLessonsDTO_id_lex', to='api.lexemes'),
        ),
    ]
