# Generated by Django 3.2.9 on 2022-04-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rulesdto_id_lex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesdto',
            name='vl_var',
            field=models.ManyToManyField(blank=True, null=True, to='api.Vl'),
        ),
    ]
