# Generated by Django 3.2.9 on 2022-04-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_rulesdto_vl_var'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSpent',
            fields=[
                ('login', models.CharField(max_length=200, primary_key=True, serialize=False,)),
                ('time_spent', models.IntegerField()),
            ],
            options={
                'db_table': 'user_time_spent',
                'managed': False,
            },
        ),
    ]
