# Generated by Django 3.2.9 on 2022-04-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_timespent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesdto',
            name='side',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
