# Generated by Django 3.2.9 on 2022-04-28 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_rulesdto_vl_var'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vl',
        ),
    ]
