# Generated by Django 3.2.9 on 2022-04-28 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_delete_vl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('label', models.CharField(max_length=100)),
                ('id_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vl_var', to='api.rulesdto')),
            ],
        ),
    ]
