# Generated by Django 3.2.9 on 2022-04-28 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_vl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulesdto',
            name='forlesson',
        ),
    ]
