# Generated by Django 3.2.9 on 2022-04-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rulesdto_forlesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesdto',
            name='id_var',
            field=models.ManyToManyField(blank=True, null=True, to='api.Lexemes'),
        ),
    ]
