# Generated by Django 3.2.9 on 2022-04-29 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_rulesdto_id_var'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vl',
            name='id_r',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vl_var', to='api.rulesdto'),
        ),
    ]
