# Generated by Django 3.2.9 on 2022-04-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_forlessonsdto_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrasesdto',
            old_name='type',
            new_name='type_ex',
        ),
    ]
