# Generated by Django 3.2.9 on 2022-04-29 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_type_phrasesdto_type_ex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialogdto',
            old_name='type',
            new_name='type_ex',
        ),
        migrations.RenameField(
            model_name='lexdto',
            old_name='type',
            new_name='type_ex',
        ),
        migrations.RenameField(
            model_name='rulesdto',
            old_name='type',
            new_name='type_ex',
        ),
    ]
