# Generated by Django 3.2.9 on 2022-04-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_dialogdto_forlesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialogdto',
            old_name='picture',
            new_name='pic_video',
        ),
    ]
