# Generated by Django 3.2.9 on 2022-04-30 23:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20220430_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lexdto',
            name='id_miss',
        ),
        migrations.AddField(
            model_name='lexdto',
            name='id_miss',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
