# Generated by Django 3.2.9 on 2022-04-30 23:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20220501_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexdto',
            name='id_miss',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
