# Generated by Django 3.2.9 on 2022-05-01 08:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20220501_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrasesdto',
            old_name='lexeme',
            new_name='id_rep',
        ),
        migrations.AddField(
            model_name='phrasesdto',
            name='forlesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='phrases', to='api.forlessonsdto'),
        ),
        migrations.RemoveField(
            model_name='phrasesdto',
            name='id_miss',
        ),
        migrations.AddField(
            model_name='phrasesdto',
            name='id_miss',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='phrasesdto',
            name='id_variant',
            field=models.ManyToManyField(blank=True, null=True, related_name='PhrasesDTO_lex_id_variant', to='api.Lexemes'),
        ),
    ]
