# Generated by Django 3.2.9 on 2022-05-01 10:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20220501_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogdto',
            name='id_miss',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='dialogdto',
            name='id_rep',
            field=models.ManyToManyField(blank=True, null=True, related_name='DialogDTO_lex_id_lex', to='api.Replicas'),
        ),
        migrations.AlterField(
            model_name='dialogdto',
            name='pic_video',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VlVarPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('label', models.CharField(max_length=100)),
                ('id_phrasedto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vl_variant', to='api.phrasesdto')),
            ],
        ),
        migrations.CreateModel(
            name='VlMissPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('label', models.CharField(max_length=100)),
                ('id_phrasedto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vl_miss', to='api.phrasesdto')),
            ],
        ),
    ]
