# Generated by Django 3.2.9 on 2022-05-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20220501_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='VlRep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('label', models.CharField(max_length=100)),
                ('id_diadto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vl_rep', to='api.dialogdto')),
            ],
        ),
        migrations.CreateModel(
            name='VlMissD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('label', models.CharField(max_length=100)),
                ('id_diadto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vl_miss', to='api.dialogdto')),
            ],
        ),
    ]
