# Generated by Django 3.2.9 on 2022-05-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20220501_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulesdto',
            name='id_lex',
        ),
        migrations.AddField(
            model_name='rulesdto',
            name='id_lex',
            field=models.ManyToManyField(blank=True, null=True, related_name='RulesDTO_lex_id_lex', to='api.Lexemes'),
        ),
    ]
