# Generated by Django 3.2.9 on 2022-05-01 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20220501_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lexdto',
            old_name='id_variant',
            new_name='id_var',
        ),
        migrations.AlterField(
            model_name='vlvar',
            name='id_lexdto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vl_var', to='api.lexdto'),
        ),
    ]
