# Generated by Django 3.2.9 on 2022-05-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_dialogdto_pic_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlvarphrase',
            name='id_phrasedto',
        ),
        migrations.RemoveField(
            model_name='phrasesdto',
            name='id_rep',
        ),
        migrations.AddField(
            model_name='phrasesdto',
            name='id_rep',
            field=models.ManyToManyField(blank=True, null=True, related_name='PhrasesDTO_rep_id_rep', to='api.Replicas'),
        ),
        migrations.DeleteModel(
            name='VlMissPhrase',
        ),
        migrations.DeleteModel(
            name='VlVarPhrase',
        ),
    ]
