# Generated by Django 3.2.9 on 2022-05-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_rename_id_variant_phrasesdto_id_var'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('login', models.CharField(primary_key=True, max_length=200, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('photo', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField()),

            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='vllex',
            name='id_lexdto',
        ),
        migrations.RemoveField(
            model_name='vlmiss',
            name='id_lexdto',
        ),
        migrations.RemoveField(
            model_name='vlmissd',
            name='id_diadto',
        ),
        migrations.RemoveField(
            model_name='vlrep',
            name='id_diadto',
        ),
        migrations.RemoveField(
            model_name='vlvar',
            name='id_lexdto',
        ),
        migrations.DeleteModel(
            name='Vl',
        ),
        migrations.DeleteModel(
            name='VlLex',
        ),
        migrations.DeleteModel(
            name='VlMiss',
        ),
        migrations.DeleteModel(
            name='VlMissD',
        ),
        migrations.DeleteModel(
            name='VlRep',
        ),
        migrations.DeleteModel(
            name='VlVar',
        ),
    ]
