# Generated by Django 3.2.9 on 2022-05-01 21:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_numstop'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeakPoints',
            fields=[
                ('login', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('weak', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
            options={
                'db_table': 'weak_points',
                'managed': False,
            },
        ),
    ]
