# Generated by Django 3.2.9 on 2022-05-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_weakpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfWeakPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name_les', models.TextField()),
                ('count', models.IntegerField()),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'number_of_weak_points',
                'managed': False,
            },
        ),
    ]
