# Generated by Django 3.2.9 on 2022-05-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_numberofweakpoints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeakPoints',
        ),
    ]
