# Generated by Django 3.2.9 on 2022-05-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_delete_weakpoints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumStop',
        ),
    ]
