# Generated by Django 3.2.9 on 2022-05-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_progressblocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeakPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name_les', models.TextField()),
                ('total', models.IntegerField()),
                ('completed', models.IntegerField()),
                ('count', models.IntegerField()),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'for_weak_points_dto',
                'managed': False,
            },
        ),
    ]
