# Generated by Django 3.2.9 on 2022-05-02 22:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_weakpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name_les', models.TextField()),
                ('total', models.IntegerField()),
                ('completed', models.IntegerField()),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            options={
                'db_table': 'for_weak_dto',
                'managed': False,
            },
        ),
    ]
