# Generated by Django 3.2.9 on 2022-05-02 23:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_weaks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteDTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('id_ex', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
            options={
                'db_table': 'delete_dto',
                'managed': False,
            },
        ),
    ]
