# Generated by Django 3.2.9 on 2022-05-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_forlessonsdto_lessonblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forlessonsdto',
            name='lessonblock',
            field=models.IntegerField(null=True),
        ),
    ]
