# Generated by Django 3.2.9 on 2022-05-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_forlessonsdto_lessonblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulesdto',
            name='forlesson',
        ),
        migrations.AddField(
            model_name='forlessonsdto',
            name='rules',
            field=models.ManyToManyField(blank=True, null=True, related_name='RulesDTO', to='api.RulesDTO'),
        ),
        migrations.AlterField(
            model_name='rulesdto',
            name='sound_rule',
            field=models.FileField(unique=True, upload_to='images/'),
        ),
    ]
