# Generated by Django 3.2.9 on 2022-05-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20220506_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesdto',
            name='picture',
            field=models.TextField(),
        ),
    ]
