# Generated by Django 3.2.9 on 2022-05-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_rulesdto_sound_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forlessonsdto',
            name='rules',
        ),
        migrations.AddField(
            model_name='rulesdto',
            name='forlesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rules', to='api.forlessonsdto'),
        ),
    ]
