# Generated by Django 3.2.9 on 2022-05-08 23:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0066_auto_20220506_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeakPoints',
        ),
    ]
